### ISSUE TITLE
基礎編（basic）

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/GitMaster#1]
GitMaster - http://sunstripe.main.jp/GitMaster

**関連情報**  
はじめに #17
TODO #81

コンセプト
---
目的
---
用語などを紹介する

**TODO**  
- **状態**
- **リンク**
- [x] 入門編 - 項目リンク追加
- [x] 入門編 - ファイル追加 - #12 
- [x] 【リリース作業】 - [basic](http://sunstripe.main.jp/GitMaster/basic.html)
- [x] 【テスト作業】 #85 
- **デザイン**
- [ ] 基礎編（basic）：一覧 - デザイン #120 
- [ ] 基礎編（basic）：詳細 - デザイン #121 

## 機能一覧
- [ ] 機能一覧
- [ ] 機能（１）
- [ ] 機能（２）

## 画面一覧
- [ ] 画面遷移図
- [ ] 一覧画面
- [ ] 詳細画面
- [ ] 画面（１）
- [ ] 画面（２）

---

**掲載内容**

---

**head**
title = Git Master - 入門編
discription = Git Master - 入門編 - basic
keyword = Git,入門編,basic

**header**
mainMenu = 
menu = 
- [x] 区切り線 #18
---
**contetns**
- [x] タイトル作成 #14
- [x] #4 Gitの基本 - はじめに
- [ ] #5 リポジトリの共有
- [ ] #6 変更履歴を統合

**ad**

**page**

**footer**

**Comment by youbinoyou** [comment]
- [ ] #4
