### ISSUE TITLE
はじめに読むもの（README.md）

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/GitMaster#17]
**関連情報**  
はじめに #17

**状態**  
- [ ] はじめに読むもの - 項目リンク追加
- [x] はじめに読むもの - ファイル追加 - [README.md](http://sunstripe.main.jp/GitMaster/README.md)
- [x] GitMaster
- [ ] サンストライプ：メンバー
- [ ] ファイル構成
- [ ] 画面一覧
- [ ] 機能一覧

**◉GitMaster**
- [ ] タイトル
- [ ] 説明
- [ ] バージョン

**◉サンストライプ：メンバー**

- [x] 大島 曜 追加

**◉ファイル構成**

画面一覧
**メインページ**
- [x] index.html - ランディングページ index
- [x] basic.html - 基礎編 basic #1 
- [x] expansion.html - 応用編 expansion #2 
- [x] reference.html -  リファレンス - reference Reference #3  
**基礎編**
- [x] basicStart.html はじめに #4 
**応用編**
- [x] branch.html - branch #7 
- [x] gitFlow.html - Git Flow #74
**リファレンス**
- [ ] ガイド guide
- [ ] 目次 contents

**ミニコンテンツ**
**Git Flow**
- [x] develop.html - developブランチ #76 
- [x] feature.html - featureブランチ #78 
- [x] hotfix.html - hotfixブランチ #79
- [x] master.html - masterブランチ #75 
- [x] release.html - releaseブランチ #77

機能一覧

**表示系**

**header**
- [ ] Logoページリンク機能
- [x] メインメニュー機能
- [ ] サイドメニュー機能
- [ ] イマココ機能
- [x] サブメニュー機能
- [x] 最終更新日の機能
- [ ] シェア機能

**contents**
- [x] 記事機能
- [ ] コラム機能
- [ ] QR表示機能

**ad**
- [ ] スポンサーリンク機能
- [ ] AD広告機能 ー 【表示準備】

**page**
- [x] ページング機能
- [ ] 関連一覧機能
- [ ] おすすめアプリケーション機能
- [ ] Amazonリンク機能
- [ ] GA機能 #21

**footer**
- [x] CopyRight機能

**操作系**
- [ ] topに上がる機能

**SNS系**
- [ ] facebookへの投稿機能
- [ ] Twitterへの投稿機- [ ] いいね機能
- [ ] いいね解除機能
- [ ] コメント数表示機能
- [ ] コメントを投稿する機能
- [ ] コメントを削除する機能
- [ ] 最近のコメント一覧表示機能

**管理系**
- [ ] カレンダー機能
- [ ] プロフィール機能
- [ ] 人気の投稿機能
- [ ] 最近の投稿機能
- [ ] レコメンド機能
- [ ] カテゴリ一覧表示機能
- [ ] ストック機能
- [ ] タグ機能
- [ ] 検索機能
- [ ] 評価機能
- [ ] Good機能
- [ ] Bad機能
- [ ] 母国変換機能

**編集系**
- [ ] 記事編集機能
- [ ] 記事削除機能
- [ ] 画像投稿機能
- [ ] 画像削除機能
- [ ] オーナー登録機能
- [ ] メンバー登録機能
- [ ] 会員登録機能
- [ ] 仮登録機能
- [ ] フリー登録機能

必要かどうか画面一覧
- [ ] About
- [ ] Documentation
- [ ] Book
- [ ] Videos
- [ ] External Links
- [ ] Blog
- [ ] Downloads
- [ ] Community

サイトではない機能一覧

- [ ] メルマガ
- [ ] アプリ化？

**◉リリース方法**
 - [ ] リリースフローチャート

**Comment by youbinoyou** [comment]
画面一覧
- [ ] ガイド guide
- [ ] 目次 contents
- [ ] 基礎編 basic #1 
- [ ] 発展編 expansion #2 
- [ ] リファレンス reference

機能一覧
- [ ] topに上がる機能
- [ ] facebookへの投稿機能
- [ ] Twitterへの投稿機能
- [x] 最終更新日の機能
- [ ] ページング機能
- [ ] イマココ機能
- [ ] CopyRight機能
- [ ] Logoページリンク機能
- [ ] おすすめアプリケーション機能
- [ ] レコメンド機能
- [ ] 母国変換機能
- [ ] 検索機能
