### ISSUE TITLE
Gitリファレンス（reference）

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/GitMaster#3]
GitMaster - http://sunstripe.main.jp/GitMaster

**関連情報**  
はじめに #17
TODO #81

コンセプト
---
目的
---
リファレンスなどを紹介する

**TODO**  
- **状態**
- [x] リファレンス - 項目リンク追加
- [x] リファレンス - ファイル追加 - [reference](http://sunstripe.main.jp/GitMaster/reference.html)
- [ ] 文章
- [ ] ヘッダー
- [ ] 関連リンク
- [ ] フッター
- **リンク**
- **デザイン**
- [ ] Gitリファレンス（reference）：一覧 - デザイン #122 
- [ ] Gitリファレンス（reference）：詳細 - デザイン #123 

## 機能一覧
- [ ] 機能一覧
- [ ] 機能（１）
- [ ] 機能（２）

## 画面一覧
- [ ] 画面遷移図
- [ ] 一覧画面
- [ ] 詳細画面
- [ ] 画面（１）
- [ ] 画面（２）

---

**ad**

**page**

**footer**

- [x] 項目リンク追加
- [x] ファイル追加

**head**

|項目名|表示内容|
|--|--|
title | リファレンス - reference| 
discription|ここでは、様々なGitのリファレンスを紹介していきます。|

- [ ] title
- [ ] discription

**header**

|項目名|表示内容|
|--|--|
mainMenu | 
menu |--|
title | リファレンス
english | reference
maintitle | reference（リファレンス）

- [ ] mainMenu
- [ ] menu
- [x] title
- [x] english
- [x] maintitle

**contetns** #108 

## 目的で探す
|項目名|表示内容|
|--|--|
| **基本操作** 
menu | 基本操作
menu | ブランチ操作
menu | 統合操作
menu | リベース操作
menu | タグ操作
menu | コミットログ操作
menu | Stash操作
| **応用操作** 
menu|応用操作
menu|SSH接続設定
menu|Git設定
menu|Git-Subversion比較
menu|トラブルシューティング

- 基本操作
- [ ] 基本操作 - http://sunstripe.main.jp/GitMaster/basicStart.html
- [ ] ブランチ操作
- [ ] 統合操作
- [ ] リベース操作
- [ ] タグ操作
- [ ] コミットログ操作
- [ ] Stash操作
- 応用操作
- [ ] 応用操作
- [ ] SSH接続設定
- [ ] Git設定
- [ ] Git-Subversion比較
- [ ] トラブルシューティング

## A to Z other
|項目名|表示内容|
|--|--|
menu | a b c d e f g h
menu | i j k l m n o p
menu | q r s t u v w x
menu | y z other
要望項目|
0001 |テーブルで表示を安定させる（要望：ボタンタップしやすく見やすくする

# 目的で探す

**基本操作**

|項目名|表示内容|
|--|--|
menu | 基本操作
description | Gitの基本操作を学びます
**リポジトリを作成したい**|
menu | リポジトリを作成したい
description | リポジトリを作成したい
**ファイルをインデックスに登録したい**|
menu | ファイルをインデックスに登録したい
description | ファイルをインデックスに登録したい
**ディレクトリをインデックスに登録したい**|
menu | ディレクトリをインデックスに登録したい
description | ディレクトリをインデックスに登録したい
**インデックスに追加されたファイルをコミットしたい**|
menu | インデックスに追加されたファイルをコミットしたい
description | インデックスに追加されたファイルをコミットしたい
**ディレクトリをインデックスに登録したい**|
menu | ディレクトリをインデックスに登録したい
description | ディレクトリをインデックスに登録したい
**インデックスに追加されたファイルをコミットしたい**|
menu | インデックスに追加されたファイルをコミットしたい
description | インデックスに追加されたファイルをコミットしたい
**変更されたファイルの一覧を表示したい**|
menu | 変更されたファイルの一覧を表示したい
description | 変更されたファイルの一覧を表示したい
**変更されたファイルの差分を見たい**|
menu | 変更されたファイルの差分を見たい
description | 変更されたファイルの差分を見たい
**コミットログを見たい**|
menu | コミットログを見たい
description | コミットログを見たい
**コミットの詳細を確認したい**|
menu | コミットの詳細を確認したい
description | コミットの詳細を確認したい
**ファイル名を変更したい**|
menu | ファイル名を変更したい
description | ファイル名を変更したい

ディレクトリ名を変更したい
ディレクトリ名を変更したい

ファイルやディレクトリ名を変更したい、移動したい
ファイルやディレクトリ名を変更したい、移動したい

ファイルを移動したい
ファイルを移動したい

ディレクトリを移動したい
ディレクトリを移動したい

ファイルを削除したい
ファイルを削除したい

管理対象ではないファイルを削除したい
管理対象ではないファイルを削除したい

以前にコミットしたことのあるファイルだけをすべてインデックスに登録したい
以前にコミットしたことのあるファイルだけをすべてインデックスに登録したい

手元で変更したインデックスに登録されていないファイルを元に戻したい
手元で変更したインデックスに登録されていないファイルを元に戻したい

インデックスに登録したファイルを取り消したい
インデックスに登録したファイルを取り消したい

ブランチ操作
ブランチ操作
Gitのブランチ操作を学びます

ブランチの一覧を表示したい
ブランチの一覧を表示したい

ブランチを作成したい
ブランチを作成したい

ブランチ名を変更したい
ブランチ名を変更したい

ブランチを削除したい
ブランチを削除したい

ブランチを切り替えたい
ブランチを切り替えたい

ブランチを統合したい
rebase - リベース

ブランチをマージしたい
ブランチをマージしたい

統合操作
統合操作
Gitの統合操作を学びます

マージで統合したい
merge - マージ

リベースで統合したい
rebase - リベース

リベース操作
リベース操作
Gitのリベース操作を学びます

rebaseを途中で中止したい
rebaseを途中で中止したい

rebaseをなかったことにしたい
rebaseをなかったことにしたい

タグ操作
タグ操作
Gitのタグ操作を学びます

タグの一覧を表示したい
タグの一覧を表示したい

タグを作成したい
タグを作成したい

注釈付きタグを作成したい
注釈付きタグを作成したい

タグを削除したい
タグを削除したい

コミットログ操作
コミットログ操作
Gitのコミットログ操作を学びます

直前のコミットの内容を修正したい
直前のコミットの内容を修正したい

直前のコミットのコメントだけを修正したい
直前のコミットのコメントだけを修正したい

過去のコミットの内容を修正したい
過去のコミットの内容を修正したい

過去のコミットのコメントだけを修正したい
過去のコミットのコメントだけを修正したい

特定のコメントを含むコミットを探したい
特定のコメントを含むコミットを探したい

直前のコミットをなかったことにしたい
直前のコミットをなかったことにしたい

ブランチを間違えてしまったコミットを移動したい
ブランチを間違えてしまったコミットを移動したい

Stash操作
Stash操作
GitのStash操作を学びます

現在の作業を一時的に退避したい
現在の作業を一時的に退避したい

退避した作業の一覧を表示したい
退避した作業の一覧を表示したい

退避した作業を復元したい
退避した作業を復元したい

退避した作業を削除したい
退避した作業を削除したい

退避した作業を全て削除したい
退避した作業を全て削除したい

応用操作
応用操作
Gitの応用操作を学びます

HEADの移動履歴を見たい
HEADの移動履歴を見たい

ブランチの先頭の移動履歴を見たい
ブランチの先頭の移動履歴を見たい

直前のresetをなかったことにしたい
直前のresetをなかったことにしたい

リモート操作
リモート操作
Gitのリモート操作を学びます

既存のリモートリポジトリを複製したい
既存のリモートリポジトリを複製したい

リモートリポジトリを追加したい
リモートリポジトリを追加したい

リモートリポジトリの一覧を表示したい
リモートリポジトリの一覧を表示したい

リモートリポジトリのブランチからローカルリポジトリのブランチを作成したい
リモートリポジトリのブランチからローカルリポジトリのブランチを作成したい

リモートリポジトリにブランチを作成したい
リモートリポジトリにブランチを作成したい

リモートリポジトリにブランチに変更内容を反映したい
リモートリポジトリにブランチに変更内容を反映したい

リモートリポジトリのブランチの変更内容を確認したい
リモートリポジトリのブランチの変更内容を確認したい

リモートリポジトリのブランチの変更内容を取り込みたい
リモートリポジトリのブランチの変更内容を取り込みたい

リモートリポジトリのブランチを削除したい
リモートリポジトリのブランチを削除したい

リモートリポジトリにタグを作成したい
リモートリポジトリにタグを作成したい

リモートリポジトリのタグを削除したい
リモートリポジトリのタグを削除したい

登録済みのリモートリポジトリのアドレスを変更したい
登録済みのリモートリポジトリのアドレスを変更したい

登録済みのリモートリポジトリの名前を変更したい
登録済みのリモートリポジトリの名前を変更したい

SSH接続設定
SSH接続設定
GitのSSH接続設定を学びます

SSH接続を設定したい(Windows)
SSH接続を設定したい(Windows)

SSH接続を設定したい(Mac)
SSH接続を設定したい(Mac)

SSH接続を設定したい(コンソール)
SSH接続を設定したい(コンソール)

BacklogにSSH鍵を設定したい
BacklogにSSH鍵を設定したい

GithubにSSH鍵を設定したい
GithubにSSH鍵を設定したい

Git設定
Git設定
Git設定を学びます

ユーザ名を設定したい
ユーザ名を設定したい

メールアドレスを設定したい
メールアドレスを設定したい

出力をカラーリングしたい設定の一覧を表示したい
出力をカラーリングしたい設定の一覧を表示したい

コマンドにエイリアスを設定したい
コマンドにエイリアスを設定したい

不要なファイルを管理対象外にしたい
不要なファイルを管理対象外にしたい

空ディレクトリを管理対象としたい
空ディレクトリを管理対象としたい

設定の一覧を表示したい
設定の一覧を表示したい

プロキシサーバを経由してhttp接続したい
プロキシサーバを経由してhttp接続したい

ユーザ認証の必要なプロキシサーバを経由してhttp接続したい
ユーザ認証の必要なプロキシサーバを経由してhttp接続したい

Git-Subversion比較
Git-Subversion比較
Git-Subversion比較

Git-Subversionコマンド比較表
Git-Subversionコマンド比較表

トラブルシューティング
トラブルシューティング
Gitのトラブルシューティングを学びます

SSH
リモートに接続しようとしたときに、”Permission denied (publickey).” と表示されます
リモートに接続しようとしたときに、”Permission denied (publickey).” と表示されます

HTTPS
cloneできません
cloneできません

push/pull するときに毎回パスワードを聞かれます
push/pull するときに毎回パスワードを聞かれます

SSH/HTTPS 共通
pushしても、リモートリポジトリに反映されません
pushしても、リモートリポジトリに反映されません

A - Z other
a
b
branch - ブランチ
履歴の流れを分岐して記録していくためのもの

c
check out - チェックアウト
ヘッドを切り替えること
過去のコミットを対象にチェックアウトした場合、それをもとにコミットすることはできない

clone - クローン
リモートリポジトリをコピーしてローカルリポジトリを作成すること

commit - コミット
インデックスに登録してある変更対象をローカルリポジトリに反映すること

confrict - コンフリクト
マージ対象の２ファイルで同じ箇所が変更されており、自動でマージができないこと

d
develop - ディベロップ
ディベロップ

e
f
feature - フィーチャー
フィーチャー

fetch - フェッチ
リモートリポジトリの変更をローカルリポジトリに反映させること
フェッチ＋マージ

fork - フォーク
リモートリポジトリをコピーしてリモートリポジトリを作成すること

g
git - ギット
ギット

Git Flow - ギットフロー
ギットフロー

GitHub Flow - ギットハブフロー
ギットハブフロー

gitgnore - ギットイグノア
履歴管理の対象外とするファイルを登録するところ
対象範囲は各リポジトリ

【P R】Gitが、おもしろいほどわかる基本の使い方33　改訂新版
【P R】 Gitが、おもしろいほどわかる基本の使い方33〈バージョン管理、SourceTree、Bitbucket〉  

h
head - ヘッド
作業対象となっているブランチ、コミット

hotfix - ホットフィックス
ホットフィックス

hunk - ハンク
変更した一範囲

i
index - インデックス
コミットしたいファイル又はファイルの一部を登録するところ。

【P R】いちばんやさしいGit&GitHubの教本
【P R】いちばんやさしいGit&GitHubの教本 人気講師が教えるバージョン管理&共有入門 (「いちばんやさしい教本」シリーズ)  

j
k
l
m
master - マスター
マスター

merge - マージ
異なるブランチの変更を反映させること
お互いの変更履歴が残る

n
【P R】ノンプログラマーなMacユーザーのためのGit入門
【P R】ノンプログラマーなMacユーザーのためのGit入門  

o
p
push - プッシュ
ローカルリポジトリの変更をリモートリポジトリに反映させること

pull - プッシュ
リモートリポジトリの変更をローカルリポジトリに反映させること
フェッチ＋マージ

pull request - プルリクエスト
フォークしたリポジトリでの変更を、フォーク元のリポジトリへ反映するよう依頼すること

q
r
repository - リポジトリ
履歴管理を行う場所

remote repository - リモート リポジトリ
サーバーにあるリポジトリ。基本はベアリポジトリで運用される。

local repository - ローカル リポジトリ
自分のPCにあるリポジトリ。基本はノンベアリポジトリで運用される

bare repository - ベア リポジトリ
ワークツリーを持たず、チェックアウト、マージができないリポジトリ

non bare repository - ノンベア リポジトリ
ワークツリーを持ち、チェックアウト、マージができるリポジトリ

rebase - リベース
異なるブランチの変更を反映させること
変更履歴が片方に集約される

release - リリース
リリース

reset - リセット
コミット前の変更をローカルリポジトリの状態へ戻すこと
また、特定のコミットまで状態を戻すこと。ただし、ローカルリポジトリに限られる

s
stage - ステージ
ワークツリーからコミットしたいファイル又はファイルの一部をIndexに登録すること。

t
tag - タグ
タグ

u
v
w
work tree - ワークツリー
履歴管理を行いたいファイルがある場所

【P R】 わかばちゃんと学ぶ Git使い方入門
【P R】 わかばちゃんと学ぶ Git使い方入門  

x
y
z
other
.gitgnore - ドットギットイグノア
履歴管理の対象外とするファイルを登録するところ
対象範囲は各リポジトリ

.gitgnore（グローバル） - ドットギットイグノア（グローバル）
履歴管理の対象外とするファイルを登録するところ
対象範囲は全リポジトリ
