### ISSUE TITLE
Gitの基本 - はじめに （basicStart）：TODO

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/GitMaster#4]
GitMaster - http://sunstripe.main.jp/GitMaster

**関連情報**  
はじめに #17
TODO #81

コンセプト
---
目的
---
Gitの基本を紹介する

#1

チュートリアル - レイアウト

**状態**  
- [x] はじめに - 項目リンク追加
- [x] はじめに - ファイル追加 - [basicStart](http://sunstripe.main.jp/GitMaster/basicStart.html) #12
- [ ] 文章
- [ ] ヘッダー
- [ ] 関連リンク
- [ ] フッター

**内容**  

**head**
title = 
discription = 

**header**
mainMenu = 
menu = 

**contetns**
- [ ] #65 Gitバージョン管理 - 項目リンク追加
- [ ] Gitバージョン管理 - ファイル追加 - [basicGitVersion](http://sunstripe.main.jp/GitMaster/basicGitVersion.html)
- [ ] #66 履歴管理 - レポジトリ - 項目リンク追加
- [ ] 履歴管理 - レポジトリ - ファイル追加 - [basicGitRepository](http://sunstripe.main.jp/GitMaster/basicGitRepository.html)
- [ ] #67 変更履歴 - コミット - 項目リンク追加
- [ ] 変更履歴 - コミット - ファイル追加 - [basicGitCommit](http://sunstripe.main.jp/GitMaster/basicGitCommit.html)
- [ ] #68 ワークツリー - 項目リンク追加
- [ ] ワークツリー - ファイル追加 - [basicGitWorkTree](http://sunstripe.main.jp/GitMaster/basicGitWorkTree.html)
- [ ] #69 インデックス - 項目リンク追加
- [ ] インデックス - ファイル追加 - [basicGitIndex](http://sunstripe.main.jp/GitMaster/basicGitIndex.html)

**ad**

**page**

**footer**
