### ISSUE TITLE
WIP : 変更履歴を統合 - basicMerge：TODO

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/GitMaster#6]
**関連情報**  
はじめに #17
#1

**状態**  
- [ ] 変更履歴を統合 - 項目リンク追加
- [ ] 変更履歴を統合 - ファイル追加 - [basicMerge](http://sunstripe.main.jp/GitMaster/basicMerge.html)
- [ ] 文章
- [ ] ヘッダー
- [ ] 関連リンク
- [ ] フッター

**head**
title = 
discription = 

**header**
mainMenu = 
menu = 

**contetns**

**ad**

**page**

**footer**

- [ ] #6 変更履歴のmerge - 項目リンク追加
- [ ] 変更履歴のmerge - ファイル追加
- [ ] #70 結合解決（conflict） - 項目リンク追加
- [ ] 結合解決（conflict） - ファイル追加
