### ISSUE TITLE
release ブランチ（release）：TODO

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/GitMaster#77]
**関連情報**  
はじめに #17
TODO #83
#74 

**状態**  
- [x] release ブランチ - 項目リンク追加
- [x] release ブランチ - ファイル追加 - [release](http://sunstripe.main.jp/GitMaster/release.html) #40
- [ ] 文章
- [ ] ヘッダー
- [ ] 関連リンク
- [ ] フッター

**head**
title = Git Master - Git Flow
discription = Git Master - Git Flow

**header**
mainMenu = 
menu = 

**contetns**

**ad**

**page**

**footer**

- [x] Git Flow - gitFlow.html - 【項目追加】
- [x] Git Flow - gitFlow.html - 【ファイル追加】
- [x] master ブランチ - master.html - 【項目追加】
- [x] master ブランチ - master.html - 【ファイル追加】
- [x] develop ブランチ - develop.html - 【項目追加】
- [x] develop ブランチ - develop.html - 【ファイル追加】
- [x] release ブランチ - release.html - 【項目追加】
- [x] release ブランチ - release.html - 【ファイル追加】
- [x] feature ブランチ - feature.html - 【項目追加】
- [x] feature ブランチ - feature.html - 【ファイル追加】
- [x] hotfix ブランチ - hotfix.html - 【項目追加】
- [x] hotfix ブランチ - hotfix.html - 【ファイル追加】

**機能**
- [ ] 機能
