### ISSUE TITLE
feature ブランチ（feature）：TODO

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/GitMaster#78]
**関連情報**  
はじめに #17
TODO #83
#74 

**状態**  
- [x] feature ブランチ - 項目リンク追加
- [x] feature ブランチ - ファイル追加 - [feature](http://sunstripe.main.jp/GitMaster/feature.html) #22
- [ ] 文章
- [ ] ヘッダー
- [ ] 関連リンク
- [ ] フッター

**head**
- [x] title = Git Master - Git Flow - feature #30
discription = Git Master - Git Flow - feature

**header**
mainMenu = 
menu = 

**contetns**
- [x] トピック削除 #32 

**ad**
- [x] 広告枠追加 #31
- [ ] 広告機能

**page**
- [x] ページめくり機能 #27

**footer**
- [x] コピーライト #26 #28 #29
 
- [x] Git Flow - gitFlow.html - 【項目追加】
- [x] Git Flow - gitFlow.html - 【ファイル追加】
- [x] master ブランチ - master.html - 【項目追加】
- [x] master ブランチ - master.html - 【ファイル追加】
- [x] develop ブランチ - develop.html - 【項目追加】
- [x] develop ブランチ - develop.html - 【ファイル追加】
- [x] release ブランチ - release.html - 【項目追加】
- [x] release ブランチ - release.html - 【ファイル追加】
- [x] feature ブランチ - feature.html - 【項目追加】
- [x] feature ブランチ - feature.html - 【ファイル追加】
- [x] hotfix ブランチ - hotfix.html - 【項目追加】
- [x] hotfix ブランチ - hotfix.html - 【ファイル追加】

**機能**
- [ ] 機能 

**緊急対応**
- リンクエラーになっていた #41 
- リンク先にブランチが含まれていたので削除 #41 
- 飛べなかったリンクをリンクできるようにする #43
