### ISSUE TITLE
【テスト作業】 - ver1.0.0：TODO

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/GitMaster#83]
**関連情報**  
TODO #81 

**テスト項目：TODO**

**ver1.0.0**

画面一覧
**メインページ**
- [x] テスト作業：#84 [index](http://sunstripe.main.jp/GitMaster/index.html) - ランディングページ index TODO作業：#80
- [x] テスト作業：#85 [basic](http://sunstripe.main.jp/GitMaster/basic.html) - 基礎編 basic TODO作業：#1 
- [x] テスト作業：#86 [expansion](http://sunstripe.main.jp/GitMaster/expansion.html) - 応用編 expansion TODO作業：#2 
- [x] テスト作業：#87 [reference](http://sunstripe.main.jp/GitMaster/reference.html) -  リファレンス - reference Reference TODO作業：#3  
**基礎編**
- [x] テスト作業：#88 [basicStart](http://sunstripe.main.jp/GitMaster/basicStart.html) はじめに - basicStart TODO作業：#4 
**応用編**
- [x] テスト作業：#89 [branch](http://sunstripe.main.jp/GitMaster/branch.html) - branch TODO作業：#7 
- [x] テスト作業：#90 [gitFlow](http://sunstripe.main.jp/GitMaster/gitFlow.html) - Git Flow TODO作業：#74

**ミニコンテンツ**
**Git Flow**
- [x] テスト作業：#91 [develop](http://sunstripe.main.jp/GitMaster/develop.html) - developブランチ TODO作業：#76 
- [x] テスト作業：#92 [feature](http://sunstripe.main.jp/GitMaster/feature.html) - featureブランチ TODO作業：#78 
- [x] テスト作業：#93 [hotfix](http://sunstripe.main.jp/GitMaster/hotfix.html) - hotfixブランチ TODO作業：#79
- [x] テスト作業：#94 [master](http://sunstripe.main.jp/GitMaster/master.html) - masterブランチTODO作業： #75 
- [x] テスト作業：#95 [release](http://sunstripe.main.jp/GitMaster/release.html) - releaseブランチ TODO作業：#77

**Comment by youbinoyou** [comment]
**index**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**basic**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**expansion**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**referense**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**reference**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**reference**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**reference**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**reference**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
gitFlow

**Comment by youbinoyou** [comment]
develop

**Comment by youbinoyou** [comment]
develop

**Comment by youbinoyou** [comment]
**feature**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**hotfix**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**hotfix**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**

**Comment by youbinoyou** [comment]
**release**

機能一覧

**表示系**

**header**
- [ ] メインメニュー機能
- [ ] サブメニュー機能
- [ ] 最終更新日の機能

**contents**
- [ ] 記事機能

**ad**

**page**
- [ ] ページング機能

**footer**
- [ ] CopyRight機能

**操作系**

**SNS系**

**管理系**

**編集系**
